version: "2.4"
services:
  server:
    build: ./
    ports:
      - "3000:3000"
    environment:
      DB_URI: mongodb://database:27017/parse
    links:
      - db:database
    depends_on:
      - db
  db:
    image: mongo:latest